apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  volumes:
    - name: data
      azureFile:
        secretName: <azure-secret>
        shareName: <share-name>
        readOnly: false
  containers:
    - image: alpine
      name: my-app
      volumeMounts:
        - mountPath: /data/storage
          name: data